name: zzz [DO NOT RUN] Close Inactive Issues
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    if: github.repository_owner == 'nightscout'
    steps:
      - uses: actions/stale@v9.0.0
        with:
          days-before-issue-stale: 30
          days-before-issue-close: 14
          stale-issue-label: "stale"
          stale-issue-message: "hey ğŸ‘‹ - silence for 30 days ğŸ¤ ... anybody? triage is required!"
          close-issue-message: "closed ğŸ“´ because silencio ğŸ¤« since an additional 14 days after staleness ğŸ“ "
          close-issue-label: "not-planned"
          exempt-issue-labels: "needs-triage, long-term, in-progress"
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          

  close-issues-triage:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    if: github.repository_owner == 'nightscout'
    steps:
      - uses: actions/stale@v9.0.0
        with:
          days-before-issue-stale: 30
          days-before-issue-close: 30
          stale-issue-label: "stale"
          stale-issue-message: "hey ğŸ‘‹ - no triage is done for 30 days ğŸ¤ ... anybody? triage is required!"
          close-issue-message: "closed ğŸ“´ because silencio ğŸ¤« since an additional 30 days after staleness ğŸ“ "
          close-issue-label: "not-planned"
          exempt-issue-labels: "long-term, in-progress"
          any-of-labels: "needs-triage"
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}

